version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lojinha
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build: ./api   # Caminho para a sua aplicação Node.js
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/lojinha
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db-data:
